version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.netty:netty-codec-http
    versions:
    - 4.1.58.Final
  - dependency-name: org.apache.logging.log4j:log4j-slf4j-impl
    versions:
    - 2.14.0
  - dependency-name: io.reactivex.rxjava2:rxjava
    versions:
    - 2.2.20
  - dependency-name: com.pusher:pusher-java-client
    versions:
    - 2.2.5
  - dependency-name: io.netty:netty-handler
    versions:
    - 4.1.45.Final
